services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --protected-mode no
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./backend
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      FLASK_ENV: production
      PYTHONUNBUFFERED: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVICE_DISCOVERY_BACKEND: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./backend:/app/backend
      - ./frontend/static:/app/static
      #- ./frontend/templates:/app/templates
      - ./uploads:/app/uploads
      - ./datasets:/app/datasets
      - ./runs:/app/runs

  frontend:
    build: ./frontend
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network


  generator:
    build: ./generator-service
    container_name: generator_service
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://app:5000
      - HOSTNAME=generator-1
    depends_on:
      - app
      - redis
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge